apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-orders-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "projeto-final.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
