environment: staging

image:
  tag: stg

imagePullSecrets:
  - name: ghcr-secret
  
postgres:
  credentials:
    password: "staging-troque-esta-password"

oidc:
  clientSecret: "troque-este-segredo-service-orders-staging"