environment: staging

image:
  tag: stg
  pullSecretName: microk8s-staging-pull


postgres:
  credentials:
    password: "staging-troque-esta-password"

oidc:
  clientSecret: "troque-este-segredo-service-orders-staging"